### ISSUE TITLE
"Async" method suffix analyzer/codefix

### ISSUE THREAD

**Issue by christian-sheridan** [GuOrg/Gu.Analyzers#234]
https://docs.microsoft.com/en-us/dotnet/csharp/async#important-info-and-advice
You should add "Async" as the suffix of every async method name you write.

incorrect:
```csharp
public async Task<Person> GetPerson() { }
public async Task DoSomething() { }
```

correct:
```csharp
public async Task<Person> GetPersonAsync() { }
public async Task DoSomethingAsync() { }
```

**Comment by JohanLarsson** [comment]
This analyzer and fix already exists in [Microsoft.VisualStudio.Threading.Analyzers](https://github.com/microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD200.md).
